def create_pr_title(plan):
    return f"Fix: {plan.problem}"

def create_pr_body(plan):
    body = f"""
## Problem
{plan.problem}
---
## Root Cause
{plan.root_cause}
---
## Implementation
"""
    for step in plan.implementation_steps:
        body += f"- {step}\n"
    body += "\n---\n"
    body += "Generated by AutoFix AI 🤖"
    return body